GPIO.out(TREE, 1)
sleep(1)
GPIO.out(TREE, 0)
sleep(1)
GPIO.out(TREE, 1)
GPIO.out(SANTA_HOUSE, 1)
GPIO.out(POST_OFFICE, 1)
sleep(2)
GPIO.out(TREE, 0)
GPIO.out(SANTA_HOUSE, 0)
GPIO.out(POST_OFFICE, 0)
sleep(1)
for _ in range(10):
    GPIO.out(TREE, 1)
    sleep(0.25)
    GPIO.out(TREE, 0)
    sleep(0.25)
